server:
  address: 0.0.0.0
  port: 8080

spring:
  application:
    name: ${cloud.microservice.name}
  cloud:
    gateway:
      routes:
        - id: rewrite-actions-log-and-proxy-to-catalog
          uri: ${qip.internal-services.runtime-catalog}
          predicates:
            - Path=/v1/actions-log/**
          filters:
            - RewritePath=/v1/actions-log/?(?<segment>.*), /v1/catalog/actions-log/$\{segment}
        - id: rewrite-imports-instructions-and-proxy-to-catalog
          uri: ${qip.internal-services.runtime-catalog}
          predicates:
            - Path=/v1/import-instructions/**
          filters:
            - RewritePath=/v1/import-instructions/?(?<segment>.*), /v1/catalog/import-instructions/$\{segment}
        - id: proxy-to-catalog
          uri: ${qip.internal-services.runtime-catalog}
          predicates:
            - Path=/**
          filters:
            - RewritePath=/(?<segment>.*), /$\{segment}     # forward full path without prefix rewriting

management:
  endpoints:
    web:
      exposure:
        exclude: shutdown
        include: info, health, ready, env, loggers, metrics, prometheus

logging:
  level:
    root: ${ROOT_LOG_LEVEL:INFO}
  config: classpath:logback-spring.xml

qip:
  internal-services:
    runtime-catalog: http://runtime-catalog:8080
